# ==============================================================================
# ProGuard / R8 Rules for Battery Health Tracker
# ==============================================================================

# --- 1. Shizuku API (Binder IPC & Service Management) ---
# Preserve all Shizuku AIDL interfaces, providers, and Binder wrappers.
-keep class rikka.shizuku.** { *; }
-keep interface rikka.shizuku.** { *; }
-keep class moe.shizuku.** { *; }
-keep interface moe.shizuku.** { *; }
-dontwarn rikka.shizuku.**
-dontwarn moe.shizuku.**

# --- 2. Room Database & Persistence ---
# Preserve entities, DAOs, and database implementations generated by KSP.
-keep class * extends androidx.room.RoomDatabase
-keep class com.fivestars.batterytracker.BatteryData { *; }
-keep interface com.fivestars.batterytracker.BatteryDao { *; }
-keep class com.fivestars.batterytracker.BatteryDao_Impl { *; }
-keep class com.fivestars.batterytracker.AppDatabase_Impl { *; }
-dontwarn androidx.room.paging.**

# --- 3. Android WorkManager ---
# Preserve Worker classes instantiated via reflection by WorkManager.
-keep class * extends androidx.work.Worker { *; }
-keep class * extends androidx.work.ListenableWorker { *; }
-keep class com.fivestars.batterytracker.BatteryWorker { *; }

# --- 4. Application Models, Presets, and Enums ---
# Preserve data transfer classes and enums.
-keep class com.fivestars.batterytracker.BatterySnapshot { *; }
-keep class com.fivestars.batterytracker.DeviceBatteryPreset { *; }
-keep class com.fivestars.batterytracker.ReleaseInfo { *; }
-keep class com.fivestars.batterytracker.UpdateCheckResult** { *; }
-keep class com.fivestars.batterytracker.BatteryViewModel$BatteryProjection { *; }
-keep enum com.fivestars.batterytracker.** { *; }

# --- 5. Kotlin Coroutines & Standard Rules ---
-dontwarn kotlinx.coroutines.**
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable
